### ISSUE TITLE
Checkpoint 1 is ready for review

### ISSUE THREAD

**Issue by Han434** [Han434/pocketedDays#1]
@pawaitemadisoncollege checkpoint 1 is ready for review

**Comment by pawaitemadisoncollege** [comment]
Hi @Han434 You are off to a great start here!!! 

**User stories**

Your user stories are well-thought-out and thorough! They cover the interaction with the database (full CRUD - create, read, update, and delete). 

- [x] I am not sure if there is a story that includes consuming a restful web service or api with Java code? Perhaps the contact us page or the help us improve page could use JavaMail or a similar api to to send email?


**Project plan, Flow and Tasks**

I think laying out the various resources in your tasks page will be very helpful as you begin working on the various user stories.   
- [x] I did not see any DAOs listed, but know that you will be using one to access the database (the servlets won't directly access the database). 
- [x] I think some entity classes may be missing as well - you'll typically have one entity class per database table.
- [x] Your project plan is missing some details - It would be a good idea to lay out which user stories you will complete each week. This can help ensure you are able to complete everything by the end of the semester. I also recommend adding tasks for peer reviews, incorporating peer review feedback, Checkpoint 2, Checkpoint 3, deploying to AWS, and preparing your end of semester presentation.

**Screen design**

Excellent work on this - I think the level of detail you included will make building the jsps much easier. They are also useful for understanding what fields the database will have.

**Reflection statements/time log** 

- [x] You only need to keep track of your time in one place - either the reflection or the time log. The time log appears to be empty, so perhaps this should be removed?
- [x] Be sure to keep your weekly reflection up-to-date!
