### ISSUE TITLE
Checkpoint 2 is ready for review

### ISSUE THREAD

**Issue by Han434** [Han434/pocketedDays#6]
@pawaitemadisoncollege
Checkpoint 2 is ready. Could you possibly give me feedback regarding many many relations?

**Comment by pawaitemadisoncollege** [comment]
Hi @Han434! Overall, you have a done a nice job hitting checkpoint 2. Below are some of my findings from a review checkpoint 2 items:

**Database designed and created**

- [x] Row has a creatorID, but I don't see a relationship in the ERD to the User table.

**At least one DAO with full CRUD (create, read, update, delete) implemented with Hibernate**

- [x] I think your User table and Project table should have a set of UserProjects. You may find this reference helpful when annotating entities for a many-to-many relationship with a join table with extra columns: https://mkyong.com/hibernate/hibernate-many-to-many-example-join-table-extra-column-annotation/. 

**DAO is fully unit tested**

- [x] Unit testing should be improved by also testing the relationships in the various delete scenarios. For example, if I delete a user that has projects, or sheets, or rows, or user projects, what should happen to the other side?  Should the project be deleted? Write tests to make sure what _should_ happen, _does_ happen.

**Log4J is implemented (no System.out.printlns)**

- [x] a couple sneaky prints here, that I think are on your radar, but just in case, I wanted to call them out here: https://github.com/Han434/pocketedDays/blob/241cf925caeea621cdf875547a3798ace7397e7c/src/main/java/com/pocketedDays/utilities/PropertiesLoader.java#L30-L35

**Project Plan/time log/journal**

It looks like you are doing a good job updating the weekly reflection. The project plan would be most useful if the completed items were checked off:

- [X] demonstrating a completed item.

**Comment by Han434** [comment]
@pawaitemadisoncollege 
I am aware that you are busy these days. But could you please leave some feedback on the improvement that I made related to the above suggestion?
Thanks. I appreciate it.

**Comment by pawaitemadisoncollege** [comment]
Hi @Han434 Looks like some very good progress! 

I just reviewed the main branch of your repository:

- [x] It looks like you have inserting records with the various relationships tested pretty well, and this does a good job testing that rows are properly deleted when a sheet is deleted. https://github.com/Han434/pocketedDays/blob/a1ec3d14455d4e87e034609dd00cb9ab94d2afec/src/test/java/com/pocketedDays/persistence/SheetDaoTest.java#L141-L154. I think it would be a good idea to test the other side of the relationship delete too, if a row is deleted, what should happen to the sheet?  Apply this same testing to all relationships, making sure that if one side is deleted the other side either remains or is deleted as your business rules dictate. 
- [x] Regarding any database/erd improvements you made, is there a new erd showing changes? (It's quite a bit quicker for me to review a diagram than the raw sql).
- [x] I am not seeing project plan items checked off as complete: https://github.com/Han434/pocketedDays/blob/main/Documents/projectPlan.md
- [x] I did a search for "print" in GitHub to see if there were any of those hanging around, and found one here: https://github.com/Han434/pocketedDays/blob/a1ec3d14455d4e87e034609dd00cb9ab94d2afec/src/main/java/com/pocketedDays/controller/CreateSheetServlet.java#L84, that should be replaced with a log statement so that the stack trace isn't written only to the console or server log.

A few other things I noticed as I was reviewing this:

- [x] Is the StoredCredential in tokens something that is sensitive and you might not want shared? If so, best to remove it completely from GitHub. Same concern for the cognito properties, client secret, and password in the hibernate config file. 
- [x] It looks like you started building a service to provide some data - making calls from the front end directly to the service may allow you to avoid needing so many servlets. Doing this is not required, but I just thought I'd mention it in case you were heading down this path.

I did not run your application locally, but will test out the full application as part of the Checkpoint 3 review when this is deployed to AWS.
